# Generated by Django 5.0.4 on 2024-10-13 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
